### ISSUE TITLE
STDPMechanism Difference From pyNN

### ISSUE THREAD

**Issue by WemboLi** [SpiNNakerManchester/PyNNExamples_OLD#11]
In PyNNExamples/examples/stdp_example.py, "stdp_model = sim.STDPMechanism( 
                timing_dependence=sim.SpikePairRule(tau_plus=10.0, tau_minus=10.0
                                                  ,nearest=True),
                weight_dependence=sim.AdditiveWeightDependence(w_min=0, w_max=1,
                                                               A_plus=0.001, A_minus=0.0012))"
There are A_plus and A_minus as parameters in weight_dependence, however, when I check pyNN neuron models for class STDPMechanism http://neuralensemble.org/docs/PyNN/_modules/pyNN/standardmodels/synapses.html#AdditiveWeightDependence, parameters A_plus and A_minus are in timing_dependence instead of weight_dependence, is there some difference in STDPMechanism in spinnaker? 

And my second question is that, what is the length of the LTP and LTD time window in STDPMechanism? This piece of info is important for the settings of simulation parameters.

**Comment by neworderofjamie** [comment]
The reason for this is that SpiNNaker supports the PyNN 0.7 API rather than the 0.8 API that documentation points to. The PyNN 0.7 API is documented here http://neuralensemble.org/trac/PyNN/wiki/API-0.7.

In answer to your second question, the lengths of the LTP and LTD windows are defined by exponentials with the time constants specified by tau_plus and tau_minus.

Cheers

Jamie

**Comment by WemboLi** [comment]
Okay, got to know. Thanks!

Wenbo
